// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.


user_pref("general.autoScroll", true);
user_pref("general.smoothScroll.msdPhysics.enabled", true);
user_pref("gl.require-hardware", true);
user_pref("layers.acceleration.force-enabled", true);
user_pref("mousewheel.min_line_scroll_amount", 50);
